# Data Science Project Configuration

# Data paths
data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  external_data_path: "data/external"
  
# Model configuration
models:
  model_save_path: "models"
  random_state: 42
  test_size: 0.2
  validation_size: 0.2
  
# Visualization settings
visualization:
  figure_size: [12, 8]
  dpi: 300
  style: "seaborn-v0_8"
  color_palette: "Set2"
  save_path: "visualizations"
  
# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_file: "logs/data_science.log"
  
# Database configuration (if needed)
database:
  # host: "localhost"
  # port: 5432
  # database: "data_science_db"
  # username: "user"
  # password: "password"
  
# API configuration (if needed)
api:
  # base_url: "https://api.example.com"
  # api_key: "your_api_key_here"
  # timeout: 30
  
# Feature engineering
features:
  categorical_encoding: "one_hot"
  numerical_scaling: "standard"
  handle_missing: "median"
  
# Model hyperparameters
hyperparameters:
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    
  xgboost:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 6
    
  neural_network:
    hidden_layers: [128, 64, 32]
    dropout_rate: 0.2
    learning_rate: 0.001
    epochs: 100
    batch_size: 32